#!/bin/bash           

# Ingest a single PSIMS NetCDF into Postgres
# run with 'automate_psims_one [absolutepath2psimsnetcdf]
#
# Note:
# This script assumes that EDE is located at /home/sthaler/EDE
# and postgis is located at /home/sthaler/postgis
#

FILE_NETCDF=$1
FILE_TABLEIDS=${FILE_NETCDF}_tableids
FILE_TEXT=${FILE_NETCDF}_text
INGEST_ONLY_META=ingest_only_meta.py
RASTER2TEXT=/var/www/postgis/raster/loader/raster2text
COPY_CMD='copy grid_data(meta_id, var_id, date, rast) from '\'${FILE_TEXT}\'

TIME_START=$SECONDS
python ${INGEST_ONLY_META} ${FILE_NETCDF}
TIME_INGEST_ONLY_META=$(($SECONDS - $TIME_START))
TIME_START=$SECONDS
${RASTER2TEXT} ${FILE_NETCDF} -t 10x10 -tids ${FILE_TABLEIDS} -o ${FILE_TEXT}
TIME_GENERATE_TEXT=$(($SECONDS - $TIME_START))
TIME_START=$SECONDS
psql -U postgres -d ede -c "${COPY_CMD}"
TIME_COPY_FROM=$(($SECONDS - $TIME_START))

rm ${FILE_TABLEIDS} ${FILE_TEXT}

echo 'Elapsed time to ingest only metadata: '${TIME_INGEST_ONLY_META}
echo 'Elapsed time to generate text format: '${TIME_GENERATE_TEXT}
echo 'Elapsed time to do the copy from: '${TIME_COPY_FROM} 
