#!/bin/bash           

urls_file=../crawler/urls_out

while read line           
do          
	echo "ingesting... $line" 
	wget $line
	filename=${line##*/}	
	python ingest.py $filename
	rm $filename 
done <$urls_file
