#!/usr/bin/env python

from netCDF4 import Dataset
import sys

filename = sys.argv[1]
variable = sys.argv[2]

fh = Dataset(filename)

out = open('out', 'w')

vals = fh.variables[variable][:]
for x in range(360):
	for y in range(720):
		ts = vals[:,x,y]
		out.write(str(ts.count()))
		out.write('\n')
out.close()
